# TU2 executable SHA-256: 447652ffa8abe4c7b8bed590a3887efc23e1181fd836b7a3192b8a2a37ddf80f
# Relocated from base-disc hints; see ../relocations.json.

# Base entry 0x82D1DE50
[functions."0x82D26010"]
size = 12

# Base entry 0x82FAD978
[functions."0x82FB6C70"]
size = 252

# Base entry 0x82FE5EE0
[functions."0x82FEF1D8"]
size = 24

# Base entry 0x82FE5EF8
[functions."0x82FEF1F0"]
size = 12
