# TU2 executable SHA-256: 447652ffa8abe4c7b8bed590a3887efc23e1181fd836b7a3192b8a2a37ddf80f
# Relocated from base-disc hints; see ../relocations.json.

# Base entry 0x82FE9448
[functions."0x82FF2740"]
size = 4

# Base entry 0x82FEB0C0
[functions."0x82FF43B8"]
size = 4

# Base entry 0x82FEC3F8
[functions."0x82FF56F0"]
size = 4
