# Shared TU2 build integration; guest code is independent of the host OS.
set(REXSDK_DIR "" CACHE PATH "Path to rexglue-sdk source tree")
if(REXSDK_DIR)
    add_subdirectory("${REXSDK_DIR}" rexglue-sdk)
else()
    find_package(rexglue 0.10.0 REQUIRED CONFIG)
endif()
set(_generated "${CMAKE_CURRENT_SOURCE_DIR}/generated/tu2")
if(NOT EXISTS "${_generated}/sources.cmake")
    message(FATAL_ERROR "Run python scripts/codegen_title_update.py to generate TU2 sources first")
endif()
file(READ "${_generated}/source-xex.sha256" _tu2_source_hash)
string(STRIP "${_tu2_source_hash}" _tu2_source_hash)
if(NOT _tu2_source_hash STREQUAL "447652ffa8abe4c7b8bed590a3887efc23e1181fd836b7a3192b8a2a37ddf80f")
    message(FATAL_ERROR "TU2 generated sources do not match the verified executable; regenerate")
endif()
include("${_generated}/sources.cmake")

function(rexglue_setup_target target)
    add_library(${target}_recomp OBJECT ${GENERATED_SOURCES})
    target_include_directories(${target}_recomp PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/src" "${_generated}")
    target_link_libraries(${target}_recomp PRIVATE rex::runtime)
    rexglue_apply_target_settings(${target}_recomp)
    target_precompile_headers(${target}_recomp PRIVATE "${_generated}/diablo3_pch.h")
    if(WIN32)
        if(MSVC)
            target_compile_options(${target}_recomp PRIVATE /EHa)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            target_compile_options(${target}_recomp PRIVATE -fasync-exceptions)
        endif()
    else()
        target_compile_options(${target}_recomp PRIVATE -g0)
    endif()
    target_include_directories(${target} PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/src" "${_generated}")
    target_link_libraries(${target} PRIVATE ${target}_recomp rex::runtime ${CMAKE_DL_LIBS})
    rexglue_configure_target(${target} GPU_PLUGINS xenos)
    # The installed SDK stages plugins but does not stage the runtime DSO.
    add_custom_command(TARGET ${target} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
            $<TARGET_FILE:rex::runtime> $<TARGET_FILE_DIR:${target}>)
endfunction()
